### ISSUE TITLE
Windows上运行报错800A03F6

### ISSUE THREAD

**Issue by Sunshycheer** [raawaa/jav-scrapy#1]
这是我的运行环境
- Windows 10 Pro x64
- node v4.2.1
- npm 2.14.7

在执行``npm install``后，会报错``npm WARN package.json jav-scarpy@0.3.0 No repository field.``

运行``jav -h``时，Windows Script Host会弹出报错
> 脚本： G:/jav_scrapy/jav.js
>行    ： 1
>字符：1
>错误：无效字符
>代码：800A03F6
>源  ：Microsoft JScript编译错误

请问这是什么原因？我没有Google到合适的解决方法

**Comment by raawaa** [comment]
npm 的 warning 不用管，不影响功能。

你是不是在 jav-scrapy 目录里运行的 `jav -h` ？这样的话会直接运行 `jav.js` 这个文件而没有调用 Node.js。这都是因为 Windows 不认识第一行的 Shebang 写法造成的，在 Linux 下不会有这样的问题。

### 解决方案

- 不要在 jav-scrapy 目录下使用 `jav` 命令
- 如果在 jav-scrapy 目录下，可以使用 `node jav.js -h` 这样的用法

**Comment by Sunshycheer** [comment]
@raawaa 
感谢你的回复，根据你的解决方案我试了一下，果然成功了呢~

不过还遇到一些问题，比如指定保存位置后不能自动创建目录，需要自己创建目录并创建一个``.txt``文件才能正常保存，远不如默认保存方便。愿这个问题能够得以修复

**Comment by raawaa** [comment]
@Sunshycheer , 本 Issue 就此关闭，保存位置的问题我明天看看。

**Comment by raawaa** [comment]
@Sunshycheer 你说的保存的问题确实存在，已经另立 Issue #3
