### ISSUE TITLE
Mac下安装出现错误

### ISSUE THREAD

**Issue by jiayuanfa** [raawaa/jav-scrapy#18]
iOSdeMac-mini:jav-scrapy Jafar$ npm link
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "link"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! path /Users/ios/jav-scrapy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '/Users/ios/jav-scrapy' -> '/usr/local/lib/node_modules/jav-scarpy'
npm ERR!  { Error: EACCES: permission denied, symlink '/Users/ios/jav-scrapy' -> '/usr/local/lib/node_modules/jav-scarpy'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '/Users/ios/jav-scrapy',
npm ERR!   dest: '/usr/local/lib/node_modules/jav-scarpy' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ios/jav-scrapy/npm-debug.log
iOSdeMac-mini:jav-scrapy Jafar$ jav
-bash: jav: command not found
iOSdeMac-mini:jav-scrapy Jafar$ jav -h
-bash: jav: command not found
iOSdeMac-mini:jav-scrapy Jafar$ jav --help
-bash: jav: command not found
iOSdeMac-mini:jav-scrapy Jafar$ cd
iOSdeMac-mini:~ Jafar$ jav --help
-bash: jav: command not found
iOSdeMac-mini:~ Jafar$ ls
Applications	Documents	Library		Music		Public		ijkplayer-ios
Desktop		Downloads	Movies		Pictures	bin		jav-scrapy
iOSdeMac-mini:~ Jafar$ cd jav-scrapy/
iOSdeMac-mini:jav-scrapy Jafar$ jav --help
-bash: jav: command not found
iOSdeMac-mini:jav-scrapy Jafar$ 
怎么破？

**Comment by raawaa** [comment]
似乎是权限问题。试试在`npm link`命令前加`sudo`。
