### ISSUE TITLE
https 现在无法抓取了

### ISSUE THREAD

**Issue by jonerxq** [raawaa/jav-scrapy#20]
网址https://www.javbus5.com/
[ATOM-262] connect ETIMEDOUT 93.46.8.89:443

**Comment by raawaa** [comment]
我自己试了一下，只有个别番号有连接超时的现象，可能是网络环境问题？

**Comment by McNEET** [comment]
不一定是https的问题，域名经常挂可能是DNS问题，你试试浏览器能否打开，我也是死活打不开翻了也不行。。。我现在用www.javbus.com稳（把C:\Users\XXX\AppData\Roaming\npm\node_modules\jav-scarpy\jav.js里面改了）
