### ISSUE TITLE
图片名增加标题日期演员的办法

### ISSUE THREAD

**Issue by McNEET** [raawaa/jav-scrapy#23]
改js文件（win10路径C:\Users\XXX\AppData\Roaming\npm\node_modules\jav-scarpy\jav.js）：
将
function getItemCover(link, meta, done) {
  var fanhao = link.split('/').pop();
  var filename = fanhao + 'l.jpg';
改为
function getItemCover(link, meta, done) {
  var fanhao = link.split('/').pop();
  var temptitle = meta.title;
  var shorttitle = temptitle.substring(0, 200);
  var finaltitle = shorttitle.replace(/[\\\/\*\?\:\"\|\<\>]/g, '');
  var filename = finaltitle + ' -' + meta.actress + '['+ meta.date + '].jpg';

**Comment by McNEET** [comment]
另外我不太喜欢建那么多子文件夹，可将几处let itemOutput = output + "/" + fanhao全改为let itemOutput = output即可。小图也没什么用，去掉smallcover段落即可。
最后感谢作者

**Comment by badaoyicai** [comment]
小图怎么去除，最后一句没看懂

**Comment by raawaa** [comment]
这个东西是一年多前我老婆怀孕的时候写的，因为本职不是程序员，所以写得比较烂，居然有人硬着头皮把源代码看完我很感动💖。

过了这么久了，说实话 javascript 怎么写我已经忘光光了。所以如果有什么建议的话，欢迎提交Pull request. 😋

**Comment by zzos** [comment]
采集的磁力是json,这东西怎么用啊?不应该是磁力链接吗？我是小白

**Comment by raawaa** [comment]
@zzos 虽然这部分功能不是我原本写的，但是我可以解释一下。
json格式的文件里包含了片子的各种信息，磁链undefined表示这部片子暂时还没有磁链资源。

**Comment by zzos** [comment]
真的，我没仔细看，虽然源码本身有说明无磁链只抓取封面，但是我没王这处去想。不过这个源码让我对JavaScript提起了兴趣，哈哈

**Comment by raawaa** [comment]
@zzos 
我写这个东西的时候也是刚学，没想到后来有好几个人参与提交，现在的功能和我当初写的时候相比面目全非了。

**Comment by zzos** [comment]
给力了,我就觉得有些地方必须得手动输入，才能爬取到磁链。代码默认情况下爬取没有磁链的番，让人以为代码失效。不过还好 有用,代码也有研究的价值。
