### ISSUE TITLE
运行最后一句话sudo npm link显示找不到命令是什么问题啊

### ISSUE THREAD

**Issue by 921957877** [raawaa/jav-scrapy#45]
运行最后一句话sudo npm link显示找不到命令是什么问题啊

**Comment by raawaa** [comment]
@921957877 是什么操作系统，windows下的话没有sudo命令。

**Comment by 921957877** [comment]
ubuntu @raawaa

**Comment by alexfatc** [comment]
安装完成以后需要执行此命令：

sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by raawaa** [comment]
我本人用的archlinux，[参考了一些资料后](https://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04)，发现 @alexfatc 说的对。😋

> There is a naming conflict with the node package (Amateur Packet Radio Node Program), and the nodejs binary has been renamed from node to nodejs. You'll need to symlink /usr/bin/node to /usr/bin/nodejs or you could uninstall the Amateur Packet Radio Node Program to avoid that conflict.

**Comment by gaoqiang1** [comment]
> @921957877 是什么操作系统，windows下的话没有sudo命令。

大哥，Windows下怎么执行这个命令呀～我是小白。。。原谅我的发言
