### ISSUE TITLE
URL buscdn.life已经失效了，大佬有空可以更新下吗？

### ISSUE THREAD

**Issue by metyouth** [raawaa/jav-scrapy#54]
为什么不能用主站地址www.javbus.com 呢?

**Comment by metyouth** [comment]
因为是小白不懂怎么修改获取资源站域名，我尝试直接修改了Jav.js里的const baseUrl = 'http://www.javbus.com';
但是再执行的时候就会报错
jav-scrapy\jav.js:204
  let img = img_r[1];
                 ^

TypeError: Cannot read property '1' of null
如果更新域名不是太麻烦的话， 大佬 也可以在README里说明下，自己手动，因为内网的域名经常换的。。谢谢谢！

**Comment by raawaa** [comment]
@metyouth 这个项目好久没更新了。我这两天看一下，可能是网站结构变化过了。

> 但是再执行的时候就会报错
jav-scrapy\jav.js:204
let img = img_r[1];
^

**Comment by raawaa** [comment]
已经更新防屏蔽地址，报错的问题也修复了。你pull一下代码仓库更新试试。
