### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qiusli** [raawaa/jav-scrapy#8]
在执行jav -l 500(大于第一页的值),会发现只会解析第一页. 这个问题好像是你在提交"修正控制流上的小问题"出现的,如果改回去就对了,我没看出来什么原因.....

**Comment by raawaa** [comment]
@qiusli ，哦，我晚上回家看一下。

**Comment by wuzer** [comment]
执行 npm install 时报错
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! file /Users/Jefferson/jav-scrapy/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 29:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /Users/Jefferson/jav-scrapy/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jefferson/jav-scrapy/npm-debug.log

**Comment by raawaa** [comment]
@wuzer ，额，是我清理 package.json 的时候不小心少删一个逗号。已经修复，你 pull 个最新版看看。

**Comment by raawaa** [comment]
@qiusli 问题已修复。
